const $=s=>document.querySelector(s),messages=$('#messages'),state=$('#state'),answer=$('#answer'),mic=$('#micBtn');
function add(role,text,sources=[]){const d=document.createElement('div');d.className='msg '+role;d.textContent=text;if(sources?.length){const s=document.createElement('span');s.className='source';s.textContent=sources.map(x=>'['+x.id+'] '+x.title).join('  ·  ');d.appendChild(s)}messages.appendChild(d);messages.scrollTop=messages.scrollHeight}
function speak(text){if(!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text.replace(/\[\d+\]/g,''));u.rate=.98;u.pitch=1.02;window.speechSynthesis.speak(u)}
async function ask(t){if(!t)return;add('user',t);answer.textContent=t;state.textContent='THINKING';try{const r=await (await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text:t})})).json();add('assistant',r.text||JSON.stringify(r),r.sources||[]);answer.textContent=r.text||'Done.';state.textContent='IDLE';speak(r.text||'Done.')}catch(e){state.textContent='ERROR';answer.textContent='I could not complete that request.';add('system','Request failed: '+e)}refresh()}
$('#chat').onsubmit=e=>{e.preventDefault();const t=$('#input').value.trim();$('#input').value='';ask(t)};
document.querySelectorAll('[data-cmd]').forEach(b=>b.onclick=()=>ask(b.dataset.cmd));
$('#clear').onclick=()=>messages.innerHTML='';
mic.onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){add('system','Speech recognition is unavailable in this browser. Use text input or the optional voice backend.');return}const r=new SR();r.lang='en-US';r.interimResults=false;r.onstart=()=>{state.textContent='LISTENING';mic.classList.add('listening')};r.onresult=e=>{const t=e.results[0][0].transcript;$('#input').value=t;ask(t)};r.onerror=e=>add('system','Microphone error: '+e.error);r.onend=()=>{state.textContent='IDLE';mic.classList.remove('listening')};r.start()};
async function refresh(){try{const s=await (await fetch('/api/status')).json();$('#ram').textContent=s.system?.ram_percent!=null?s.system.ram_percent+'%':'—';$('#model').textContent=s.model?.general||'—';$('#agents').textContent=s.agents?.count??'—';$('#mcp').textContent=(s.mcp?.count??0)+' servers';$('#net').textContent='● ONLINE'}catch{$('#net').textContent='● OFFLINE'}}
refresh();