const $=s=>document.querySelector(s);const state=$('#state'),messages=$('#messages'),audit=$('#audit');
function add(role,text){const d=document.createElement('div');d.className=`msg ${role}`;d.textContent=text;messages.appendChild(d);messages.scrollTop=messages.scrollHeight}
function val(v){if(v&&typeof v==='object'){if('available' in v)return v.available?'ONLINE':'OFFLINE';return 'ONLINE'}return String(v)}
function renderStatus(s){const map=['model','memory','rag','mcp','web','system','voice','computer','python','browser','scheduler'];$('#status').innerHTML=map.map(k=>{const x=s[k]||{};const ok=x.available===false||x.online===false?'bad':'good';return `<div class="status-chip ${ok}"><span class="dot"></span>${k.toUpperCase()}<div style="color:var(--muted);font-size:10px">${val(x)}</div></div>`}).join('');$('#modules').innerHTML=map.map(k=>{const x=s[k]||{};return `<div class="mod"><span>${k}</span><b>${val(x)}</b></div>`}).join('');$('#model').textContent=s.model?.general||'—';$('#ram').textContent=s.system?.ram_percent!=null?s.system.ram_percent+'%':'—';$('#cpu').textContent=s.system?.cpu_percent!=null?s.system.cpu_percent+'%':'—';$('#net').textContent='ONLINE'}
async function refresh(){try{const s=await (await fetch('/api/status')).json();renderStatus(s)}catch(e){$('#net').textContent='OFFLINE'}}
$('#chat').onsubmit=async e=>{e.preventDefault();const t=$('#input').value.trim();if(!t)return;add('user',t);$('#input').value='';state.textContent='THINKING';$('#taskLine').textContent='PLANNING // ROUTING REQUEST';try{const r=await (await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text:t})})).json();add('assistant',r.text||JSON.stringify(r,null,2));if(r.confirmation_id)add('system','Confirmation required: '+r.confirmation_id);$('#taskLine').textContent=(r.source||r.provider||'COMPLETED').toUpperCase();}catch(err){add('system','Request failed: '+err);$('#taskLine').textContent='ERROR'}state.textContent='IDLE';refresh()};
document.querySelectorAll('[data-cmd]').forEach(b=>b.onclick=()=>{ $('#input').value=b.dataset.cmd; $('#input').focus(); });
$('#micBtn').onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){add('system','Browser speech recognition is unavailable; use text input or install a voice backend.');return}const r=new SR();r.lang='en-US';r.onstart=()=>state.textContent='LISTENING';r.onresult=e=>{$('#input').value=e.results[0][0].transcript;state.textContent='IDLE';$('#chat').requestSubmit()};r.onerror=()=>state.textContent='ERROR';r.onend=()=>{if(state.textContent==='LISTENING')state.textContent='IDLE'};r.start()};
const overlay=$('#palette');const pi=$('#paletteInput');function showPalette(){overlay.classList.remove('hidden');pi.focus();['Check system status','What is my RAM usage?','What time is it?','Remember that ...','Open Chrome'].forEach((x,i)=>{const d=document.createElement('div');d.className='palette-item';d.textContent=x;d.onclick=()=>{$('#input').value=x;overlay.classList.add('hidden');$('#input').focus()};$('#paletteResults').appendChild(d)})}$('#paletteBtn').onclick=showPalette;overlay.onclick=e=>{if(e.target===overlay)overlay.classList.add('hidden')};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();showPalette()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='m'){e.preventDefault();$('#micBtn').click()}});
function connectEvents(){const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/api/events`);ws.onmessage=e=>{const x=JSON.parse(e.data);if(x.event==='agent.state'){state.textContent=x.state;$('#taskLine').textContent=(x.intent||x.model||'WORKING').toUpperCase()}if(x.event==='task.updated'){renderTasks()}if(x.event?.startsWith('confirmation.'))add('system',`${x.event}: ${JSON.stringify(x.confirmation||x)}`);audit.textContent=(audit.textContent+'\n'+JSON.stringify(x)).slice(-2500)};ws.onclose=()=>setTimeout(connectEvents,2000)}
async function renderTasks(){try{const d=await (await fetch('/api/tasks')).json();$('#tasks').innerHTML=(d.agent||[]).slice(0,8).map(t=>`<div class="task"><b>${t.name}</b><small>${t.state} · ${Math.round(t.progress*100)}% · ${t.detail||''}</small></div>`).join('')||'<div class="task"><small>No tasks yet.</small></div>'}catch{} }
add('system','JARVIS online. Deterministic tools are checked before the local model.');refresh();renderTasks();connectEvents();
